// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_time_keys`, `line_contains_any_time`, `line_contains_tag`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PYTHON_PROCESS`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<void> initPythonEngine() =>
    RustLib.instance.api.crateApiSimpleInitPythonEngine();

Future<void> stopPythonEngine() =>
    RustLib.instance.api.crateApiSimpleStopPythonEngine();

Future<void> prepareLogs({
  required String zipPath,
  required String extractDir,
}) => RustLib.instance.api.crateApiSimplePrepareLogs(
  zipPath: zipPath,
  extractDir: extractDir,
);

Future<String?> searchInLogs({
  required String searchDir,
  required String targetTimestamp,
  required String tagKeyword,
  required int rangeMs,
}) => RustLib.instance.api.crateApiSimpleSearchInLogs(
  searchDir: searchDir,
  targetTimestamp: targetTimestamp,
  tagKeyword: tagKeyword,
  rangeMs: rangeMs,
);

Future<String> prepareLogsForZip({required String zipPath}) =>
    RustLib.instance.api.crateApiSimplePrepareLogsForZip(zipPath: zipPath);

Future<String> processFiles({
  required String targetTimestamp,
  required String zipPath,
  required String zipInnerDir,
  required String tagKeyword,
  required int rangeMs,
}) => RustLib.instance.api.crateApiSimpleProcessFiles(
  targetTimestamp: targetTimestamp,
  zipPath: zipPath,
  zipInnerDir: zipInnerDir,
  tagKeyword: tagKeyword,
  rangeMs: rangeMs,
);
