// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cleanup_extra_files`, `extract_all_tar_lz4_flat`, `extract_one_tar_lz4_flat`, `project_extract_dir`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PYTHON_PROCESS`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<void> initPythonEngine() =>
    RustLib.instance.api.crateApiSimpleInitPythonEngine();

Future<void> stopPythonEngine() =>
    RustLib.instance.api.crateApiSimpleStopPythonEngine();

Future<String> prepareLogsForZip({required String zipPath}) =>
    RustLib.instance.api.crateApiSimplePrepareLogsForZip(zipPath: zipPath);

Future<void> prepareLogs({
  required String zipPath,
  required String extractDir,
}) => RustLib.instance.api.crateApiSimplePrepareLogs(
  zipPath: zipPath,
  extractDir: extractDir,
);

Future<String> getExtractDir() =>
    RustLib.instance.api.crateApiSimpleGetExtractDir();

Future<String> getLogDir({required String zipInnerDir}) =>
    RustLib.instance.api.crateApiSimpleGetLogDir(zipInnerDir: zipInnerDir);

Future<String> processFiles({
  required String targetTimestamp,
  required String zipPath,
  required String zipInnerDir,
  required String tagKeyword,
  required int rangeMs,
}) => RustLib.instance.api.crateApiSimpleProcessFiles(
  targetTimestamp: targetTimestamp,
  zipPath: zipPath,
  zipInnerDir: zipInnerDir,
  tagKeyword: tagKeyword,
  rangeMs: rangeMs,
);
